import os
from os.path import join, dirname
from dotenv import load_dotenv
from discord_components import Select, SelectOption

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

SECRET_KEY = os.environ.get("SECRET_KEY")

WELCOME_MENU_DESCRIPTION = """
Hey! We are Minto — a Bitcoin mining platform.\n
*Mining is simple. Don't you believe it? Try to mine with us!*\n
We've removed all the unnecessary steps. To mine BTC, all you need is to buy and stake our BTCMT token, that equals a unit of Bitcoin mining power.\n
Our token is secured by actively operating equipment. To make it work **we use renewable energy sources with a neutral carbon footprint**.\n
Visit our [website](https://minto.finance/) and learn more about our project!\n
"""

INFO_MENU_DESCRIPTION = """
For additional questions or to contact us please write to <@981596992478269442> and we'll get back to you as soon as we can.
"""

INFO_MENU_LINKS = """
[Whitepaper](https://minto.finance/resources/MintoWhitepaper.pdf)
[Hashrate watcher](https://www.f2pool.com/mining-user/06510a9d9d36f01fb7cbad861fb6c4cb)
[Data center stream](https://rtsp.me/embed/Y7FAt7aF/)
"""

INFO_MENU_INFORMATION = """
Founded: <t:1607990400:D>
Owner: <@208632687227961344>
Invite: https://discord.gg/minto
"""

FIRST_LVL = """
**1 level — <@&992069707974856856>**
• Welcome! 
• Access to Discord
"""

FIFTH_LVL = """
**5 level — <@&998594548257267803>**
• Change nickname 
• Add reactions 
• Custom emojis
"""

TENTH_LVL = """
**10 level — <@&998595462615548036>**
• Special posting
"""

TWENTY_FIFTH_LVL = """
**25 level — <@&998595874932392056>**
• Access to closed chat rooms 
• Access to voice chats
"""

FIFTY_FIFTH_LVL = """
**55 level — <@&998596107754029087>**
• Token rewards 
• Custom roles and emojis
• Our adoration♥️
"""

CONTENT_ROLES = """
For participating in games and events you will get XP. The more points — the higher your level. With every level you will achieve a new role on this server, which will open up new possibilities. 
"""

INFORMATION_CHATS = """
<#981116499152502825> — news about Minto
<#981116559743418368>  — product faq 
<#981116609160691712> — environmental of Minto
<#981116667683819520> — educational publications
"""

COMMUNITY_CHATS = """
<#981116965974315019> — for communication in general
<#981117018638016572> — for roles and bots
<#981117055082315777> — announces and contests
<#981117088095686686> — fun
`#minto_arena` — for streams
<#981118133202993152> — sample discussions from other channels in Discord
<#981117432410279966> — analysis of current news and events in the world of blockchain
"""

CONTENT_CHATS = """
Two chat categories: community and information.
"""

RULES_INFO = """
``Rule 1`` **No disrespect**
Be respectful to each other's opinions. NO insults, racism or harassment please. 

``Rule 2`` **Scam**
No one should ask you to send money to the account. Please contact our moderator immediately if this happens to you. 

``Rule 3`` **No Inappropriate content**
Do not post any NSFW content and limit the use of offensive language across all channels and nicknames.

``Rule 4`` **No advertising**
We are free from all forms of advertising. Do not post referral links, discord invitations or any other invitations.

``Rule 5`` **Impersonating moderator team**
Impersonating members of the moderator team is a crime. Anyone caught doing this will be banned immediately.
"""

FAQ = {
  "When will BTCMT be listed on CEX?": "We are currently working on listing. We plan to list before 3-4Q 2022, but we don't have an exact date yet.",
  "How many tokens were sold?": "You can find out how many tokens have been sold on our [website](https://minto.finance/) or using our [smart contract.](https://hecoinfo.com/token/0x410a56541bd912f9b60943fcb344f1e3d6f09567)",
  "What's new this week?": "You can find all the updates and news on our [Telegram](https://t.me/btcmtofficial) or [Twitter](https://twitter.com/btcmtofficial) pages.",
  "What is Minto Finance?": """The Minto token is backed by actively operating Bitcoin mining hardware. There are no high entry barriers, risks, or maintenance issues for the end user. You can buy tokens to receive rewards in the same way a miner does, or you can buy and sell mining power to make money, but you don't have to deal with the hassles of traditional mining.""",
  "How are you different from other projects?": """
  We are very proud that our crypto project is eco-friendly. As you probably know, bitcoin mining consumes a lot of energy. Various other mining operations use electricity generated by burning coal, which is sourced from the power grid. We don't.Minto DeFi project uses only eco-friendly mining.

  Minto mining is neither harmful to the environment nor a source of CO2 emissions, as the electricity used to power the facility is provided by a private hydroelectric power plant. The CEO Water Mandates introduced by the UN were approved by WWF.
  """,
  "What’s the total amount of tokens available for sale?": "We have emitted 5 000 000 tokens. 250 000 of them are for the team. So, the amount available for purchase is 4 750 000.",
  "Are there any pictures of the Karelia hydro mining site and the data center?":"Watch the live feed from our data center in the Republic of Karelia via this [link](https://rtsp.me/embed/Y7FAt7aF/). And some pics [here](https://drive.google.com/drive/folders/1hLZp8WwgTHG0BmTlQzKmfgLmeiM6yWPi?usp=sharing). Look at this fantastic NY's Bloomberg [shot](https://mercury.bloomberg.com/images/382270225) from the Karelian data center.",
  "Are there any plans to increase the hashrate per 100 tokens, like in other similar projects?":"""Different projects can have similar features. For a better understanding of how BTCMT works, we recommend that you read our whitepaper. There is an option of increasing the emission and the tokenized hashrate of the projects. The emission depends on our vision of how to generate the maximum value for Minto token holders.""",
  "If bitcoin generates a fork when we are mining, could we also get the coin of the Bitcoin fork?":"""There are a lot of Bitcoin forks, but we don't mine them. The chance that the ETH/ETC scenario happens with the BTC network is minimal, so we'll just do our best to keep the long-term value of the token as high as possible.""",
  "Whom should I contact with marketing proposals?":"All offers can be sent to us by filling the form at this [link](https://form.typeform.com/to/ogEx7cA7?typeform-source=btcmt.typeform.com).",
}

OPTIONS = Select(
                placeholder = "Select something!",
                options = [
                    SelectOption(label = "What is Minto Finance?", value = "What is Minto Finance?", description="FAQ 1"),
                    SelectOption(label = "How are you different from other projects?", value = "How are you different from other projects?", description="FAQ 2"),
                    SelectOption(label = "When will BTCMT be listed on CEX?", value = "When will BTCMT be listed on CEX?", description="FAQ 3"),
                    SelectOption(label = "How many tokens were sold?", value = "How many tokens were sold?", description="FAQ 4"),
                    SelectOption(label = "What's new this week?", value = "What's new this week?", description="FAQ 5"),
                    SelectOption(label = "What’s the total amount of tokens available for sale?", value = "What’s the total amount of tokens available for sale?", description="FAQ 6"),
                    SelectOption(label = "Are there any pictures of the Karelia hydro mining site and the data center?", value = "Are there any pictures of the Karelia hydro mining site and the data center?", description="FAQ 7"),
                    SelectOption(label = "Are there any plans to increase the hashrate per 100 tokens, like in other similar projects?", value = "Are there any plans to increase the hashrate per 100 tokens, like in other similar projects?", description="FAQ 8"),
                    SelectOption(label = "If bitcoin generates a fork when we are mining, could we also get the coin of the Bitcoin fork?", value = "If bitcoin generates a fork when we are mining, could we also get the coin of the Bitcoin fork?", description="FAQ 9"),
                    SelectOption(label = "Whom should I contact with marketing proposals?", value = "Whom should I contact with marketing proposals?", description="FAQ 10"),
                ]
            )